### ISSUE TITLE
Some questions about the plugin

### ISSUE THREAD

**Issue by isle9** [evilmanimani/beets-navidrome_sync#1]
All of my files are in one big directory, and I'm planning on using the beets group option to finally group them into albums.
This will inevitably break my current Navidrome database.
So if I'm understanding what the plugin does correctly, I should be able to set up beets with my current directory and everything should continue to work.
To migrate I would need to:
1. Use beet ndpull to embed all of my Navidrome data into the beets database.
2. Rearrange all of my albums using the beets group option.
3. Rescan the Navidrome database.
4. The database breaks because the path change of all of my files.
5. Use beet ndpush to push all of my previous Navidrome data from the beets database to the Navidrome database?

**Comment by evilmanimani** [comment]
That's essentially it, specifically the data mentioned in the readme, so play counts, modified/created dates, ratings, etc. This has worked for my own library in testing, but this hasn't otherwise been substantially tested, so if you can keep me posted with your progress and/or issues that would be a help in fine tuning things.

It goes without saying please make sure you completely back up your ND & beets databases before proceeding with anything. None of the operations in the plugin should modify the actual files at all, but can't hurt to backup those as well if you have the space.
